name: Generate POM and Scan Dependencies
on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  generate-pom:
    name: Generate POM and Scan Dependencies
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: write


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Install Clojure CLI (clj)
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.10.3.986.sh
          chmod +x linux-install-1.10.3.986.sh
          sudo ./linux-install-1.10.3.986.sh

      - name: Install Leiningen (lein)
        run: |
          wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod +x lein
          sudo mv lein /usr/local/bin/

      - name: Determine project type
        run: |
          if [ -f "deps.edn" ]; then
            echo "Using deps.edn for project dependencies."
            clj -Spom
          elif [ -f "project.clj" ]; then
            echo "Using project.clj for project dependencies."
            lein pom
          else
            echo "Unable to determine project type. No deps.edn or project.clj found."
            exit 1
          fi

      - name: Run Trivy to produce SBOM
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'spdx-json'
          output: 'dependency-results.sbom.json'
          # image-ref: '.'
     

      - name: SBOM upload 
        uses: advanced-security/spdx-dependency-submission-action@v0.0.1
        with:
          filePath: "."
          filePattern: "dependency-results.sbom.json"


